server:
  port: 8080

spring:
  application:
    name: auth-system
  
  datasource:
    url: jdbc:h2:mem:auth_system;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # H2 Database for testing
  # datasource:
  #   url: jdbc:h2:mem:testdb
  #   driver-class-name: org.h2.Driver
  #   username: sa
  #   password: password
  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop
  #   show-sql: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 7200000 # 2 hours in milliseconds
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html